name: fire_one
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


 
 
  # firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  firebase_messaging: ^14.6.5
  url_launcher: ^6.1.12
  get: ^4.6.5
  image_pickers: ^2.0.4+1
  flash: ^3.0.5+1
  share_plus: ^7.1.0
  dismissible_page: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/




  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

